### ISSUE TITLE
End-to-end tracing: No consistent trace in Zipkin or Jaeger: Service invocation in .NET via HTTP -> Pub in .NET via SDK -> Sub in Go via HTTP -> Pub in Go via SDK -> Sub in .NET via SDK

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture-labs/cloud-native-sample#1]
See:
https://github.com/dapr/dapr/issues/4571

**Comment by ChristianWeyer** [comment]
This is implemented and will be released in Dapr 1.8:
https://github.com/dapr/dotnet-sdk/issues/773

**Comment by ThorstenHans** [comment]
We're running on `dapr-1.8.4` 

Can we close this @ChristianWeyer

**Comment by ThorstenHans** [comment]
.NET SDK is fixed. However, we lose track of the traces in Go SDK right now. 

Closing this issue here. 

Further progress of the bug in dapr-sdk for GoLang is tracked in #110
