### ISSUE TITLE
Conditionally enable Observability 

### ISSUE THREAD

**Issue by ThorstenHans** [thinktecture-labs/cloud-native-sample#32]
Currently Observability (especially metrics and traces) are always enabled using OpenTelemetry. This should be refactored to enable those observability features based on a condition (env var). 

This would allow integration with existing cloud infrastructure in Serverless environments like Azure Container Apps

**Comment by gingters** [comment]
Grabbing this ;)

**Comment by ThorstenHans** [comment]
Already implemented
